projects:
  test1:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: yplazhwianbl5hqoxok3r3enru
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        maxDepth: 2
      endpoints:
        prod: >-
          https://dugztzoronhftanb3ljz4a4r6y.appsync-api.us-east-1.amazonaws.com/graphql
